# Dependencies
gems:                [jekyll-paginate]
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               random writes
tagline:             'A systems engineer''s blog'
description:         'VMware virtualization/cloud, DevOps and IT infrastructure topics and howtos. Less is more.'
url:                 http://nilic.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nebojsa Ilic
  linkedin:			 nebojsailic
  github:			 nilic
  twitter:           nilic_
  email:             blog@nilic.33mail.com

# Custom vars
version:             1.0.0