# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               nilic's depot
tagline:             'A lazy blog by a systems engineer'
description:         'VMware virtualization/cloud, automation, DevOps and IT infrastructure topics and how-tos.'
url:                 http://nilic.github.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
