# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               /home/nilic/depot/
tagline:             'A systems engineer''s blog'
description:         'VMware virtualization/cloud, DevOps and IT infrastructure topics and howtos. Less is more.'
url:                 http://nilic.github.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Nebojsa Ilic
  url:               https://twitter.com/nilic_
  email:             blog@nilic.33mail.com

# Custom vars
version:             1.0.0
